# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# If you are using Rails 5.2 or newer, consider using the
# encrypted credentials feature described here:
# http://edgeguides.rubyonrails.org/security.html#custom-credentials

development:
  omniauth_provider_key: <%= ENV["BhUXVKO0G1m8Z3LskYdYbKijF"] %>
  omniauth_provider_secret: <%= ENV["xpSvM4e0NdzuRyOlHvnxPqGOVf6cGzlxuJh47bhNSF1A5s1TWv"] %>
  domain_name: example.com
  secret_key_base: d4d2ab0cbca3a9f9536f5afea4dae8942ef8d009f794f94c22bd15ef59284bb705ac16a7554593aba8025c1009fb04d0cc897ae2a0c154d7ddaa970ae7622307

test:
  secret_key_base: d4d2ab0cbca3a9f9536f5afea4dae8942ef8d009f794f94c22bd15ef59284bb705ac16a7554593aba8025c1009fb04d0cc897ae2a0c154d7ddaa970ae7622307

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  omniauth_provider_key: <%= ENV["BhUXVKO0G1m8Z3LskYdYbKijF"] %>
  omniauth_provider_secret: <%= ENV["xpSvM4e0NdzuRyOlHvnxPqGOVf6cGzlxuJh47bhNSF1A5s1TWv"] %>
  domain_name: <%= ENV["example.com"] %>
  secret_key_base: <%= ENV["d4d2ab0cbca3a9f9536f5afea4dae8942ef8d009f794f94c22bd15ef59284bb705ac16a7554593aba8025c1009fb04d0cc897ae2a0c154d7ddaa970ae7622307"] %>
  
  
